### ISSUE TITLE
Use acore_strings instead of harcoded strings

### ISSUE THREAD

**Issue by Elmsroth** [silviu20092/mod-sell-items#1]
Hello

You should consider enhance module accessibility for other speaking languages by using custom acore_strings instead of hardcoded

https://github.com/silviu20092/mod-sell-items/blob/d4ed7bb9cdab8eb68cdb6a7d00eaa281d67e21fe/src/SI.cpp#L97

https://github.com/silviu20092/mod-sell-items/blob/d4ed7bb9cdab8eb68cdb6a7d00eaa281d67e21fe/src/SI.cpp#L110

https://github.com/silviu20092/mod-sell-items/blob/d4ed7bb9cdab8eb68cdb6a7d00eaa281d67e21fe/src/SI.cpp#L211C1-L214C57

**Comment by silviu20092** [comment]
Done, thanks for the input!
